version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - echo "Installing dependencies..."
      - go get ./...
  pre_build: 
    commands:
      - echo "Running tests..."
      - go test ./...
  build:
    commands:
      - echo "Building the project..."
      - go build -o myapi
artifacts:
  files:
    - myapi
