package main

import (
	_ "apiSquads/docs" // docs is generated by Swag CLI, you have to import it.
	"apiSquads/router"

	_ "github.com/go-sql-driver/mysql"
)

// @title Squads API
// @description This API allows users to manage football teams and players. Users can enter new teams and players, update existing information, and view details.
// @schemes http
// @host localhost:8080
func main() {
	router.Initialize()
}
